# Generated by Django 3.0.4 on 2020-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshorten', '0003_auto_20200309_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hash',
            field=models.CharField(max_length=2048, null=True, unique=True),
        ),
    ]
